export const HIGHLIGHTS_DATA = [
    {
        id: 'khvamli',
        teamName: { ka: 'რ.კ. ხვამლი', en: 'RC Khvamli', fr: 'RC Khvamli' },
        years: '2010–2021',
        poster: '/images/highlights/davit-in-khvamli.webp',
        logo: '/images/highlights/davit-in-khvamli.webp',
        videoSrc: '/videos/teams/khvamli.mp4',
        previewStart: 0,
        previewEnd: 8,
    },
    {
        id: 'georgia',
        teamName: { ka: 'საქართველოს ეროვნული ნაკრები', en: 'Georgia National Team', fr: 'Équipe nationale de Géorgie' },
        years: '2020–present',
        poster: '/images/highlights/davit-in-GEO-National.webp',
        logo: '/images/highlights/davit-in-GEO-National.webp',
        videoSrc: '/videos/teams/georgia.mp4',
        previewStart: 0,
        previewEnd: 8,
    },
    {
        id: 'lou',
        teamName: 'LOU Rugby',
        years: '2021–2025',
        poster: '/images/highlights/davit-in-LOU.webp',
        logo: '/images/highlights/davit-in-LOU.webp',
        videoSrc: '/videos/teams/lou.mp4',
        previewStart: 0,
        previewEnd: 8,
    },
    {
        id: 'barbarians',
        teamName: 'Barbarians FC',
        years: '2022',
        poster: '/images/highlights/davit-in-Barbarians.jpg.webp',
        logo: '/images/highlights/Barbarian_FC_logo-inck.webp',
        videoSrc: '/videos/teams/barbarians.mp4',
        previewStart: 0,
        previewEnd: 8,
    },
    {
        id: 'larochelle',
        teamName: 'Stade Rochelais',
        years: '2025–present',
        poster: '/images/highlights/davit-in-larochelle.webp',
        logo: '/images/highlights/Stade_rochelais1_logo.webp',
        videoSrc: '/videos/teams/larochelle.mp4',
        previewStart: 0,
        previewEnd: 8,
    },
];

export default HIGHLIGHTS_DATA;
