import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    en: {
        'nav.home': 'HOME',
        'nav.bio': 'BIO',
        'nav.career': 'CAREER',
        'nav.gallery': 'GALLERY',
        'nav.highlights': 'HIGHLIGHTS',
        'nav.contact': 'CONTACT',
        'nav.media': 'MEDIA',
        'nav.partners': 'PARTNERS',
        'nav.forBrands': 'FOR BRANDS',
        'page.media.title': 'Media',
        'page.media.subtitle': 'International coverage archive and authority timeline for Davit Niniashvili',
        'page.media.stats.records': 'Total Records',
        'page.media.stats.tierA': 'Tier A Sources',
        'page.media.stats.languages': 'Languages',
        'page.media.filters.all': 'All',
        'page.media.filters.source': 'Source',
        'page.media.filters.year': 'Year',
        'page.media.filters.language': 'Language',
        'page.media.filters.type': 'Type',
        'page.media.filters.tier': 'Tier',
        'page.media.filters.featuredOnly': 'Featured Only',
        'page.media.filters.reset': 'Reset Filters',
        'page.media.archive.title': 'Media Archive',
        'page.media.pending.title': 'Pending Verification',
        'page.media.pending.subtitle': 'Provisional records awaiting final links or metadata',
        'page.media.viewSource': 'View Source',
        'page.media.linkPending': 'Link Pending',
        'page.media.backHome': 'Back to Home',
        'page.partners.title': 'Partners',
        'page.partners.subtitle': 'A strategic ecosystem of global brand collaborations.',
        'page.forBrands.title': 'Partnerships',
        'page.forBrands.whyPartner': 'Value Proposition',
        'page.forBrands.packages': 'Commercial Opportunities',
        'page.forBrands.inquiryCta': 'Direct Inquiry',
        'page.forBrands.subtitle': 'Exclusive digital partnership with a top-tier international athlete brand.',
        'page.forBrands.proof': 'Impact & Authority',
        'page.forBrands.process': 'Strategic Path',
        'page.forBrands.step1': 'Alignment Call',
        'page.forBrands.step2': 'Strategic Proposal',
        'page.forBrands.step3': 'Brand Integration',
        'home.media.title': 'International Media',
        'home.media.subtitle': 'Recent high-authority international media coverage featuring Davit Niniashvili',
        'home.media.viewAll': 'Explore Full Media',
        'home.media.open': 'Read Full Feature',
        'home.media.modal.takeaways': 'Key Takeaways',
        'home.media.modal.viewSource': 'View Original Source',
        'home.media.modal.linkPending': 'Source Currently Offline',
        'home.media.modal.allMedia': 'View Media Archive',
        'home.media.modal.close': 'Close',
        'home.hero.sponsorBadge': 'Partner Selection Active',
        'home.career.title': 'Professional Career',
        'home.career.viewFull': 'Explore Full Career',
        'home.highlights.viewGallery': 'Explore Full Archive',
        'home.partners.title': 'Partners',
        'home.partners.collaborations': 'Commercial Partners',
        'home.partners.sponsorship': 'Strategic Partnerships',
        'home.partners.primaryAvailable': 'Primary Digital Partner — Available',
        'home.partners.officialAvailable': 'Official Partners — Selection Active',
        'home.forBrands.cta': 'Partner with Niniashvili',
        'page.contact.subtitle': 'Inquiries and professional representation.',
        'home.authority.slogan': 'Love what you do \u2014 wholeheartedly!',
        'home.authority.author': 'Davit Niniashvili',
        'home.authority.positioning': 'Global Performance. Elite Authority.',
        'home.authority.status': 'Current \u2014 Top14: Stade Rochelais | Georgia national team',
        'home.authority.cta.career': 'Professional Career',
        'home.authority.cta.highlights': 'Featured Moments',
        'home.authority.kpis': [
            '4\u00d7 European Rugby Championship Winner (2021\u20132024)',
            'EPCR Challenge Cup Winner \u2014 Lyon (2021\u201322)',
            '46 International Caps \u2014 Georgia (debut 2020)',
            'Oscars du Midi Olympique Winner (2023)',
            'RugbyPass Top 100 Player \u2014 #83 (2025)',
            'Barbarian F.C. Appearance \u2014 80 minutes (2022)',
        ],
        'home.authority.svg1.title': 'European Champion',
        'home.authority.svg1.subline': '2021\u20132024',
        'home.authority.svg2.title': 'Challenge Cup',
        'home.authority.svg2.subline': 'Winner \u2014 Lyon',
        'home.authority.svg3.title': 'Top 100 Player',
        'home.authority.svg3.subline': 'RugbyPass 2025',
        'page.bio.position': 'Position',
        'page.bio.currentTeam': 'Current Team',
        'page.bio.previousTeam': 'Previous Team',
        'page.bio.nationality': 'Nationality',
        'page.bio.birthDate': 'Birth Date',
        'page.bio.about': 'About',
        'page.bio.loading': 'Updating profile...',
        'page.bio.errorTitle': 'Information Unavailable',
        'page.bio.errorSub': 'Please try again later.',
        'page.bio.pending': 'Profile narrative pending.',
        'page.career.loading': 'Loading career data...',
        'page.career.errorTitle': 'Data Unavailable',
        'page.career.errorSub': 'Please check back later.',
        'page.career.noStats': 'No statistics recorded yet.',
        'page.career.awardsTitle': 'Awards & Honors',
        'page.career.untitledAward': 'Untitled award',
        'page.career.table.season': 'Season',
        'page.career.table.team': 'Team',
        'page.career.table.competition': 'Competition',
        'page.career.table.matches': 'Matches',
        'page.career.table.tries': 'Tries',
        'page.career.table.meters': 'Meters',
        'page.career.table.defendersBeaten': 'Defenders Beaten',
        'page.career.table.lineBreaks': 'Line Breaks',
        'page.career.table.offloads': 'Offloads',
        'page.career.table.wdl': 'W-D-L',
        'page.career.table.starts': 'Starts',
        'page.career.table.points': 'Points',
        'page.career.table.cards': 'Cards',
        'page.career.table.minutes': 'Minutes',
        'page.career.section.overview': 'Career Overview',
        'page.career.section.seasons': 'Season-by-Season Statistics',
        'page.career.section.breakdown': 'Competition Breakdown',
        'page.career.meta.source': 'Source',
        'page.career.meta.lastUpdated': 'Last Updated',
    },
    ka: {
        'nav.home': 'მთავარი',
        'nav.bio': 'ბიო',
        'nav.career': 'კარიერა',
        'nav.gallery': 'გალერეა',
        'nav.highlights': 'გამორჩეული',
        'nav.contact': 'კონტაქტი',
        'nav.media': 'მედია',
        'nav.partners': 'პარტნიორები',
        'nav.forBrands': 'ბრენდებისთვის',
        'page.media.title': 'მედია',
        'page.media.subtitle': 'დავით ნინიაშვილის საერთაშორისო მედია-არქივი და ავტორიტეტული წყაროების ქრონოლოგია',
        'page.media.stats.records': 'საერთო რაოდენობა',
        'page.media.stats.tierA': 'A კატეგორიის წყაროები',
        'page.media.stats.languages': 'ენები',
        'page.media.filters.all': 'ყველა',
        'page.media.filters.source': 'წყარო',
        'page.media.filters.year': 'წელი',
        'page.media.filters.language': 'ენა',
        'page.media.filters.type': 'ფორმატი',
        'page.media.filters.tier': 'კატეგორია',
        'page.media.filters.featuredOnly': 'მხოლოდ გამორჩეული',
        'page.media.filters.reset': 'ფილტრის გასუფთავება',
        'page.media.archive.title': 'მედია არქივი',
        'page.media.pending.title': 'მოლოდინის რეჟიმში',
        'page.media.pending.subtitle': 'დაუდასტურებელი ჩანაწერები',
        'page.media.viewSource': 'წყაროზე გადასვლა',
        'page.media.linkPending': 'ბმული მიუწვდომელია',
        'page.media.backHome': 'მთავარ გვერდზე დაბრუნება',
        'page.partners.title': 'პარტნიორები',
        'page.partners.subtitle': 'გლობალური ბრენდ პარტნიორობების სტრატეგიული ეკოსისტემა.',
        'page.forBrands.title': 'პარტნიორობა',
        'page.forBrands.whyPartner': 'ღირებულება',
        'page.forBrands.packages': 'კომერციული შესაძლებლობები',
        'page.forBrands.inquiryCta': 'პირდაპირი მოთხოვნა',
        'page.forBrands.subtitle': 'ექსკლუზიური ციფრული პარტნიორობა უმაღლესი დონის საერთაშორისო სპორტსმენთან.',
        'page.forBrands.proof': 'გავლენა და ავტორიტეტი',
        'page.forBrands.process': 'სტრატეგიული გზა',
        'page.forBrands.step1': 'გაცნობითი ზარი',
        'page.forBrands.step2': 'სტრატეგიული შეთავაზება',
        'page.forBrands.step3': 'ბრენდ ინტეგრაცია',
        'home.media.title': 'საერთაშორისო მედია',
        'home.media.subtitle': 'დავით ნინიაშვილის შესახებ უახლესი საერთაშორისო ავტორიტეტული მედიაგაშუქებები',
        'home.media.viewAll': 'მედია არქივი',
        'home.media.open': 'სრულად წაკითხვა',
        'home.media.modal.takeaways': 'მთავარი აქცენტები',
        'home.media.modal.viewSource': 'წყაროზე გადასვლა',
        'home.media.modal.linkPending': 'წყარო დროებით მიუწვდომელია',
        'home.media.modal.allMedia': 'მედია არქივი',
        'home.media.modal.close': 'დახურვა',
        'home.hero.sponsorBadge': 'პარტნიორთა შერჩევა აქტიურია',
        'home.career.title': 'პროფესიული კარიერა',
        'home.career.viewFull': 'სრული კარიერული გზა',
        'home.highlights.viewGallery': 'სრული არქივი',
        'home.partners.title': 'პარტნიორები',
        'home.partners.collaborations': 'კომერციული პარტნიორები',
        'home.partners.sponsorship': 'სტრატეგიული თანამშრომლობა',
        'home.partners.primaryAvailable': 'მთავარი ციფრული პარტნიორი — ხელმისაწვდომია',
        'home.partners.officialAvailable': 'ოფიციალური პარტნიორები — შერჩევა აქტიურია',
        'home.forBrands.cta': 'პარტნიორობა ნინიაშვილთან',
        'page.contact.subtitle': 'მოთხოვნები და პროფესიული წარმომადგენლობა.',
        'home.authority.slogan': 'რასაც აკეთებ — გიყვარდეს მთელი გულით!',
        'home.authority.author': 'დავით ნინიაშვილი',
        'home.authority.positioning': 'გლობალური თამაში. ელიტარული ავტორიტეტი.',
        'home.authority.status': 'მიმდინარე პერიოდში — Top14: Stade Rochelais | საქართველოს ეროვნული ნაკრები',
        'home.authority.cta.career': 'პროფესიული კარიერა',
        'home.authority.cta.highlights': 'გამორჩეული მომენტები',
        'home.authority.kpis': [
            '4-გზის ევროპის ჩემპიონატის გამარჯვებული (2021–2024)',
            'EPCR Challenge Cup-ის გამარჯვებული — Lyon (2021–22)',
            '46 კეპი — საქართველო (დებიუტი 2020)',
            'Oscars du Midi Olympique-ის გამარჯვებული (2023)',
            'RugbyPass Top 100 მოთამაშე — #83 (2025)',
            'Barbarian F.C.-ის შემადგენლობაში თამაში — 80 წუთი (2022)',
        ],
        'home.authority.svg1.title': 'ევროპის ჩემპიონი',
        'home.authority.svg1.subline': '2021\u20132024',
        'home.authority.svg2.title': 'ჩელენჯ ქაფი',
        'home.authority.svg2.subline': 'გამარჯვებული — ლიონი',
        'home.authority.svg3.title': 'Top 100 მოთამაშე',
        'home.authority.svg3.subline': 'RugbyPass 2025',
        'page.bio.position': 'პოზიცია',
        'page.bio.currentTeam': 'მიმდინარე გუნდი',
        'page.bio.previousTeam': 'წინა გუნდი',
        'page.bio.nationality': 'მოქალაქეობა',
        'page.bio.birthDate': 'დაბადების თარიღი',
        'page.bio.about': 'ბიოგრაფია',
        'page.bio.loading': 'პროფილი ახლდება...',
        'page.bio.errorTitle': 'ინფორმაცია მიუწვდომელია',
        'page.bio.errorSub': 'გთხოვთ სცადოთ მოგვიანებით.',
        'page.bio.pending': 'ბიოგრაფია მზადდება.',
        'page.career.loading': 'მონაცემები იტვირთება...',
        'page.career.errorTitle': 'მონაცემები მიუწვდომელია',
        'page.career.errorSub': 'გთხოვთ სცადოთ მოგვიანებით.',
        'page.career.noStats': 'სტატისტიკა ჯერჯერობით არ ხელმისაწვდომია.',
        'page.career.awardsTitle': 'ჯილდოები და მიღწევები',
        'page.career.untitledAward': 'ჯილდო',
        'page.career.table.season': 'სეზონი',
        'page.career.table.team': 'გუნდი',
        'page.career.table.competition': 'ტურნირი',
        'page.career.table.matches': 'მატჩი',
        'page.career.table.tries': 'ლელო',
        'page.career.table.meters': 'მეტრი',
        'page.career.table.defendersBeaten': 'მოტყუებული მეტოქე',
        'page.career.table.lineBreaks': 'ხაზის გაჭრა',
        'page.career.table.offloads': 'ოფლოუდი',
        'page.career.table.wdl': 'მ-გ-წ',
        'page.career.table.starts': 'სტარტი',
        'page.career.table.points': 'ქულა',
        'page.career.table.cards': 'ბარათი',
        'page.career.table.minutes': 'წუთი',
        'page.career.section.overview': 'კარიერის მიმოხილვა',
        'page.career.section.seasons': 'სეზონების სტატისტიკა',
        'page.career.section.breakdown': 'ტურნირების ჭრილი',
        'page.career.meta.source': 'წყარო',
        'page.career.meta.lastUpdated': 'განახლდა',
    },
    fr: {
        'nav.home': 'ACCUEIL',
        'nav.bio': 'BIO',
        'nav.career': 'CARRI\u00c8RE',
        'nav.gallery': 'GALERIE',
        'nav.highlights': 'TEMPS FORTS',
        'nav.contact': 'CONTACT',
        'nav.media': 'M\u00c9DIAS',
        'nav.partners': 'PARTENAIRES',
        'nav.forBrands': 'POUR LES MARQUES',
        'page.media.title': 'Médias',
        'page.media.subtitle': 'Archive des couvertures internationales et chronologie des sources d’autorité autour de Davit Niniashvili',
        'page.media.stats.records': 'Documents',
        'page.media.stats.tierA': 'Sources Catégorie A',
        'page.media.stats.languages': 'Langues',
        'page.media.filters.all': 'Tout',
        'page.media.filters.source': 'Source',
        'page.media.filters.year': 'Année',
        'page.media.filters.language': 'Langue',
        'page.media.filters.type': 'Format',
        'page.media.filters.tier': 'Catégorie',
        'page.media.filters.featuredOnly': 'À la Une',
        'page.media.filters.reset': 'Réinitialiser',
        'page.media.archive.title': 'Archives Médias',
        'page.media.pending.title': 'En Attente de Vérification',
        'page.media.pending.subtitle': 'Documents provisoires en attente de métadonnées',
        'page.media.viewSource': 'Voir la Source',
        'page.media.linkPending': 'Lien en Attente',
        'page.media.backHome': 'Retour à l\'Accueil',
        'page.partners.title': 'Partenaires',
        'page.partners.subtitle': 'Un \u00e9cosyst\u00e8me strat\u00e9gique de collaborations mondiales.',
        'page.forBrands.title': 'Partenariats',
        'page.forBrands.whyPartner': 'Proposition de Valeur',
        'page.forBrands.packages': 'Opportunit\u00e9s Commerciales',
        'page.forBrands.inquiryCta': 'Demande Directe',
        'page.forBrands.subtitle': 'Partenariat digital exclusif avec une marque d\'athl\u00e8te international d\'\u00e9lite.',
        'page.forBrands.proof': 'Impact et Autorit\u00e9',
        'page.forBrands.process': 'Parcours Strat\u00e9gique',
        'page.forBrands.step1': 'Appel d\'alignement',
        'page.forBrands.step2': 'Proposition Strat\u00e9gique',
        'page.forBrands.step3': 'Int\u00e9gration de Marque',
        'home.media.title': 'Médias Internationaux',
        'home.media.subtitle': 'Couvertures médiatiques internationales récentes autour de Davit Niniashvili',
        'home.media.viewAll': 'Tout l\'espace média',
        'home.media.open': 'Lire l\'Article Complet',
        'home.media.modal.takeaways': 'Points Clés',
        'home.media.modal.viewSource': 'Voir la Source Originale',
        'home.media.modal.linkPending': 'Source Actuellement Hors Ligne',
        'home.media.modal.allMedia': 'Voir les Archives',
        'home.media.modal.close': 'Fermer',
        'home.hero.sponsorBadge': 'Sélection de partenaires active',
        'home.career.title': 'Carri\u00e8re Professionnelle',
        'home.career.viewFull': 'Explorer la carri\u00e8re compl\u00e8te',
        'home.highlights.viewGallery': 'Explorer l\'archive compl\u00e8te',
        'home.partners.title': 'Partenaires',
        'home.partners.collaborations': 'Partenaires Commerciaux',
        'home.partners.sponsorship': 'Partenariats Strat\u00e9giques',
        'home.partners.primaryAvailable': 'Partenaire digital principal \u2014 Disponible',
        'home.partners.officialAvailable': 'Partenaires officiels \u2014 S\u00e9lection active',
        'home.forBrands.cta': 'Collaborer avec Niniashvili',
        'page.contact.subtitle': 'Inqu\u00eates et repr\u00e9sentation professionnelle.',
        'home.authority.slogan': 'Aime ce que tu fais \u2014 de tout c\u0153ur!',
        'home.authority.author': 'Davit Niniashvili',
        'home.authority.positioning': 'Performance Mondiale. Autorit\u00e9 d\'\u00c9lite.',
        'home.authority.status': 'Actuellement \u2014 Top14: Stade Rochelais | \u00c9quipe nationale de G\u00e9orgie',
        'home.authority.cta.career': 'Carri\u00e8re Professionnelle',
        'home.authority.cta.highlights': 'Moments Forts',
        'home.authority.kpis': [
            '4\u00d7 Vainqueur du Championnat d\u2019Europe de Rugby (2021\u20132024)',
            'Vainqueur EPCR Challenge Cup \u2014 Lyon (2021\u201322)',
            '46 s\u00e9lections internationales \u2014 G\u00e9orgie (d\u00e9but 2020)',
            'Laur\u00e9at Oscars du Midi Olympique (2023)',
            'Joueur RugbyPass Top 100 \u2014 #83 (2025)',
            'Barbarian F.C. \u2014 80 minutes (2022)',
        ],
        'home.authority.svg1.title': 'Champion d\'Europe',
        'home.authority.svg1.subline': '2021\u20132024',
        'home.authority.svg2.title': 'Challenge Cup',
        'home.authority.svg2.subline': 'Vainqueur \u2014 Lyon',
        'home.authority.svg3.title': 'Top 100 Joueur',
        'home.authority.svg3.subline': 'RugbyPass 2025',
        'page.bio.position': 'Poste',
        'page.bio.currentTeam': '\u00c9quipe Actuelle',
        'page.bio.previousTeam': '\u00c9quipe Pr\u00e9c\u00e9dente',
        'page.bio.nationality': 'Nationalit\u00e9',
        'page.bio.birthDate': 'Date de Naissance',
        'page.bio.about': '\u00c0 Propos',
        'page.bio.loading': 'Mise \u00e0 jour du profil...',
        'page.bio.errorTitle': 'Information non disponible',
        'page.bio.errorSub': 'Veuillez r\u00e9essayer plus tard.',
        'page.bio.pending': 'Description du profil en cours.',
        'page.career.loading': 'Chargement des donn\u00e9es de carri\u00e8re...',
        'page.career.errorTitle': 'Donn\u00e9es non disponibles',
        'page.career.errorSub': 'Veuillez r\u00e9essayer plus tard.',
        'page.career.noStats': 'Aucune statistique enregistr\u00e9e pour le moment.',
        'page.career.awardsTitle': 'Prix et Distinctions',
        'page.career.untitledAward': 'Prix',
        'page.career.table.season': 'Saison',
        'page.career.table.team': '\u00c9quipe',
        'page.career.table.competition': 'Comp\u00e9tition',
        'page.career.table.matches': 'Matchs',
        'page.career.table.tries': 'Essais',
        'page.career.table.meters': 'M\u00e8tres',
        'page.career.table.defendersBeaten': 'D\u00e9fenseurs battus',
        'page.career.table.lineBreaks': 'Franchissements',
        'page.career.table.offloads': 'Offloads',
        'page.career.table.wdl': 'V-N-D',
        'page.career.table.starts': 'Titulaire',
        'page.career.table.points': 'Points',
        'page.career.table.cards': 'Cartons',
        'page.career.table.minutes': 'Minutes',
        'page.career.section.overview': 'Vue d\'ensemble',
        'page.career.section.seasons': 'Statistiques par saison',
        'page.career.section.breakdown': 'R\u00e9partition par comp\u00e9tition',
        'page.career.meta.source': 'Source',
        'page.career.meta.lastUpdated': 'Mise \u00e0 jour',
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem('site_lang');
        if (saved && ['ka', 'fr', 'en'].includes(saved)) {
            return saved;
        }
        const browserLang = navigator.language || navigator.languages?.[0];
        if (browserLang) {
            if (browserLang.toLowerCase().startsWith('ka')) return 'ka';
            if (browserLang.toLowerCase().startsWith('fr')) return 'fr';
        }
        return 'en';
    });

    useEffect(() => {
        localStorage.setItem('site_lang', language);
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
