import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    en: {
        'nav.home': 'HOME',
        'nav.bio': 'BIO',
        'nav.career': 'CAREER',
        'nav.gallery': 'GALLERY',
        'nav.highlights': 'HIGHLIGHTS',
        'nav.contact': 'CONTACT',
        'nav.media': 'MEDIA',
        'nav.partners': 'PARTNERS',
        'nav.forBrands': 'FOR BRANDS',
        'page.media.title': 'Media',
        'page.media.subtitle': 'International coverage archive and authority timeline for Davit Niniashvili',
        'page.media.stats.records': 'Total Records',
        'page.media.stats.tierA': 'Tier A Sources',
        'page.media.stats.languages': 'Languages',
        'page.media.filters.all': 'All',
        'page.media.filters.source': 'Source',
        'page.media.filters.year': 'Year',
        'page.media.filters.language': 'Language',
        'page.media.filters.type': 'Type',
        'page.media.filters.tier': 'Tier',
        'page.media.filters.featuredOnly': 'Featured Only',
        'page.media.filters.reset': 'Reset Filters',
        'page.media.archive.title': 'Media Archive',
        'page.media.pending.title': 'Pending Verification',
        'page.media.pending.subtitle': 'Provisional records awaiting final links or metadata',
        'page.media.viewSource': 'View Source',
        'page.media.linkPending': 'Link Pending',
        'page.media.backHome': 'Back to Home',
        'page.partners.title': 'Partners',
        'page.partners.subtitle': 'A strategic ecosystem of global brand collaborations.',
        'home.media.title': 'International Media',
        'home.media.subtitle': 'Recent high-authority international media coverage featuring Davit Niniashvili',
        'home.media.viewAll': 'Explore Full Media',
        'home.media.open': 'Read Full Feature',
        'home.media.modal.takeaways': 'Key Takeaways',
        'home.media.modal.viewSource': 'View Original Source',
        'home.media.modal.linkPending': 'Source Currently Offline',
        'home.media.modal.allMedia': 'View Media Archive',
        'home.media.modal.close': 'Close',
        'home.hero.sponsorBadge': 'Partner Selection Active',
        'home.career.title': 'Professional Career',
        'home.career.viewFull': 'Explore Full Career',
        'home.highlights.viewGallery': 'Explore Full Archive',
        'home.partners.title': 'Partners',
        'home.partners.collaborations': 'Commercial Partners',
        'home.partners.sponsorship': 'Strategic Partnerships',
        'home.partners.primaryAvailable': 'Primary Digital Partner — Available',
        'home.partners.officialAvailable': 'Official Partners — Selection Active',
        'home.forBrands.cta': 'Partner with Niniashvili',
        'page.contact.subtitle': 'Inquiries and professional representation.',
        'home.authority.slogan': 'Love what you do \u2014 wholeheartedly!',
        'home.authority.author': 'Davit Niniashvili',
        'home.authority.positioning': 'Global Performance. Elite Authority.',
        'home.authority.status': 'Current \u2014 Top14: Stade Rochelais | Georgia national team',
        'home.authority.cta.career': 'Professional Career',
        'home.authority.cta.highlights': 'Featured Moments',
        'home.authority.kpis': [
            '4\u00d7 European Rugby Championship Winner (2021\u20132024)',
            'EPCR Challenge Cup Winner \u2014 Lyon (2021\u201322)',
            '46 International Caps \u2014 Georgia (debut 2020)',
            'Oscars du Midi Olympique Winner (2023)',
            'RugbyPass Top 100 Player \u2014 #83 (2025)',
            'Barbarian F.C. Appearance \u2014 80 minutes (2022)',
        ],
        'home.authority.svg1.title': 'European Champion',
        'home.authority.svg1.subline': '2021\u20132024',
        'home.authority.svg2.title': 'Challenge Cup',
        'home.authority.svg2.subline': 'Winner \u2014 Lyon',
        'home.authority.svg3.title': 'Top 100 Player',
        'home.authority.svg3.subline': 'RugbyPass 2025',
        'page.bio.position': 'Position',
        'page.bio.currentTeam': 'Current Team',
        'page.bio.previousTeam': 'Previous Team',
        'page.bio.nationality': 'Nationality',
        'page.bio.birthDate': 'Birth Date',
        'page.bio.about': 'About',
        'page.bio.loading': 'Updating profile...',
        'page.bio.errorTitle': 'Information Unavailable',
        'page.bio.errorSub': 'Please try again later.',
        'page.bio.pending': 'Profile narrative pending.',
        'page.career.loading': 'Loading career data...',
        'page.career.errorTitle': 'Data Unavailable',
        'page.career.errorSub': 'Please check back later.',
        'page.career.noStats': 'No statistics recorded yet.',
        'page.career.awardsTitle': 'Awards & Honors',
        'page.career.untitledAward': 'Untitled award',
        'page.career.table.season': 'Season',
        'page.career.table.team': 'Team',
        'page.career.table.competition': 'Competition',
        'page.career.table.matches': 'Matches',
        'page.career.table.tries': 'Tries',
        'page.career.table.meters': 'Meters',
        'page.career.table.defendersBeaten': 'Defenders Beaten',
        'page.career.table.lineBreaks': 'Line Breaks',
        'page.career.table.offloads': 'Offloads',
        'page.career.table.wdl': 'W-D-L',
        'page.career.table.starts': 'Starts',
        'page.career.table.points': 'Points',
        'page.career.table.cards': 'Cards',
        'page.career.table.minutes': 'Minutes',
        'page.career.section.overview': 'Career Overview',
        'page.career.section.seasons': 'Season-by-Season Statistics',
        'page.career.section.breakdown': 'Competition Breakdown',
        'page.career.meta.source': 'Source',
        'page.career.meta.lastUpdated': 'Last Updated',
        // NEW FOR BRANDS KEYS
        'page.forBrands.s1.eyebrow': 'Business Opportunities',
        'page.forBrands.s1.title': 'Brand Partnership & Digital Collaboration Opportunities',
        'page.forBrands.s1.sub': 'The official platform for brands, agencies, and commercial representatives.',
        'page.forBrands.s1.body': 'Davit Niniashvili\'s official digital environment offers partners structured collaboration models and integration formats.',
        'page.forBrands.s1.cta1': 'Partnership Inquiry',
        'page.forBrands.s1.cta2': 'Request Media Kit',
        'page.forBrands.s2.eyebrow': 'Value',
        'page.forBrands.s2.title': 'Why Brands Partner with Davit Niniashvili',
        'page.forBrands.s2.sub': 'Athletic authority and personal brand reputation create a premium commercial environment.',
        'page.forBrands.s2.body': 'Collaboration is based on the athlete\'s sporting authority and stable personal brand value. High-quality brand alignment and digital growth potential ensure effective and structured integration.',
        'page.forBrands.s3.eyebrow': 'Taxonomy',
        'page.forBrands.s3.title': 'Partnership Models Overview',
        'page.forBrands.s3.sub': 'Classification and structure of commercial relationships.',
        'page.forBrands.s3.body': 'The system separates Brand Partner collaborations from Digital Partner tiers. This distinction allows for clearly defined collaboration formats and brand presence channels.',
        'page.forBrands.s4.eyebrow': 'Commercial Offer',
        'page.forBrands.s4.title': 'Digital Partnership Opportunities',
        'page.forBrands.s4.sub': 'Formats for brand integration on the official platform.',
        'page.forBrands.s4.body': 'This section presents the primary commercial offer for digital partnerships. From Main Digital Partner to Website Supporter, each category defines the scope of brand visibility and integration tools on the platform.',
        'page.forBrands.s4.cta': 'View Terms',
        'page.forBrands.s5.eyebrow': 'Clarification',
        'page.forBrands.s5.title': 'Brand Partnership and Digital Partnership Are Not the Same',
        'page.forBrands.s5.sub': 'Separation of commercial representation and platform integration.',
        'page.forBrands.s5.body': 'Brand Partnership focuses on the athlete\'s broader commercial representation, while Digital Partnership specifically entails integration within this platform\'s digital ecosystem.',
        'page.forBrands.s6.eyebrow': 'Platform Role',
        'page.forBrands.s6.title': 'Why the Official Platform Matters',
        'page.forBrands.s6.sub': 'Official digital presence and structured integration.',
        'page.forBrands.s6.body': 'The platform ensures an organized display of brands in a unified digital space. This is a growth-oriented environment where brand integration is managed through strategic planning.',
        'page.forBrands.s7.eyebrow': 'Reputation',
        'page.forBrands.s7.title': 'Selected Brand Collaborations',
        'page.forBrands.s7.sub': 'History of collaborations and professional associations.',
        'page.forBrands.s7.body': 'This section showcases prior or existing brand collaborations and serves strictly as reputational association. The presence of these logos does not indicate Main Digital Partner, Digital Partner, or Website Supporter status.',
        'page.forBrands.s8.eyebrow': 'Credibility',
        'page.forBrands.s8.title': 'Professional Status',
        'page.forBrands.s8.sub': 'Official platform and partnership readiness.',
        'page.forBrands.s8.body': 'The official platform serves as the athlete\'s primary digital channel, reflecting an active sporting career and collaboration experience. It is fully prepared for structured commercial partnerships.',
        'page.forBrands.s8.p1': 'Stade Rochelais — Elite Top 14 & Champions Cup',
        'page.forBrands.s8.p2': 'Georgia National Team — International Performance',
        'page.forBrands.s8.p3': 'Official Digital Platform Established',
        'page.forBrands.s8.p4': 'Structured Commercial Ecosystem & Media Kit Ready',
        'page.forBrands.s9.eyebrow': 'Conversion',
        'page.forBrands.s9.title': 'Partnership Inquiry',
        'page.forBrands.s9.sub': 'Request a media kit or submit a partnership proposal.',
        'page.forBrands.s9.body': 'We review all professional inquiries. By completing this form, you can receive a detailed media kit or ask questions about specific partnership categories.',
        'page.forBrands.s9.cta1': 'Submit Inquiry',
        'page.forBrands.s9.cta2': 'Get Media Kit',
        'page.forBrands.s10.title': 'Start Commercial Collaboration',
        'page.forBrands.s10.sub': 'Get detailed information about partnership opportunities.',
        'page.forBrands.s10.cta1': 'Fill Form',
        'page.forBrands.s10.cta2': 'Contact',
        'page.forBrands.form.company': 'Company Name',
        'page.forBrands.form.name': 'Contact Person',
        'page.forBrands.form.position': 'Position',
        'page.forBrands.form.email': 'Email',
        'page.forBrands.form.interest': 'Partnership Interest',
        'page.forBrands.form.category': 'Category of Interest',
        'page.forBrands.form.message': 'Message',
        'page.forBrands.form.submit': 'Submit Request',
        'page.forBrands.form.success': 'Local form validation successful.',
        'page.forBrands.cat.brand': 'Brand Partner',
        'page.forBrands.cat.brand.desc': 'Broader commercial collaboration and brand integration.',
        'page.forBrands.cat.mainDigital': 'Main Digital Partner',
        'page.forBrands.cat.mainDigital.desc': 'The leading digital partner of the platform.',
        'page.forBrands.cat.digital': 'Digital Partner',
        'page.forBrands.cat.digital.desc': 'A strategic partner in the digital ecosystem.',
        'page.forBrands.cat.supporter': 'Website Supporter',
        'page.forBrands.cat.supporter.desc': 'Digital supporter of the platform.',
        'page.forBrands.form.interest.inquiry': 'Partnership Inquiry',
        'page.forBrands.form.interest.mediakit': 'Media Kit Request',
        'page.forBrands.form.fallback': 'For direct contact:'
    },
    ka: {
        'nav.home': 'მთავარი',
        'nav.bio': 'ბიო',
        'nav.career': 'კარიერა',
        'nav.gallery': 'გალერეა',
        'nav.highlights': 'გამორჩეული',
        'nav.contact': 'კონტაქტი',
        'nav.media': 'მედია',
        'nav.partners': 'პარტნიორები',
        'nav.forBrands': 'ბრენდებისთვის',
        'page.media.title': 'მედია',
        'page.media.subtitle': 'დავით ნინიაშვილის საერთაშორისო მედია-არქივი და ავტორიტეტული წყაროების ქრონოლოგია',
        'page.media.stats.records': 'საერთო რაოდენობა',
        'page.media.stats.tierA': 'A კატეგორიის წყაროები',
        'page.media.stats.languages': 'ენები',
        'page.media.filters.all': 'ყველა',
        'page.media.filters.source': 'წყარო',
        'page.media.filters.year': 'წელი',
        'page.media.filters.language': 'ენა',
        'page.media.filters.type': 'ფორმატი',
        'page.media.filters.tier': 'კატეგორია',
        'page.media.filters.featuredOnly': 'მხოლოდ გამორჩეული',
        'page.media.filters.reset': 'ფილტრის გასუფთავება',
        'page.media.archive.title': 'მედია არქივი',
        'page.media.pending.title': 'მოლოდინის რეჟიმში',
        'page.media.pending.subtitle': 'დაუდასტურებელი ჩანაწერები',
        'page.media.viewSource': 'წყაროზე გადასვლა',
        'page.media.linkPending': 'ბმული მიუწვდომელია',
        'page.media.backHome': 'მთავარ გვერდზე დაბრუნება',
        'page.partners.title': 'პარტნიორები',
        'page.partners.subtitle': 'გლობალური ბრენდ პარტნიორობების სტრატეგიული ეკოსისტემა.',
        'home.media.title': 'საერთაშორისო მედია',
        'home.media.subtitle': 'დავით ნინიაშვილის შესახებ უახლესი საერთაშორისო ავტორიტეტული მედიაგაშუქებები',
        'home.media.viewAll': 'მედია არქივი',
        'home.media.open': 'სრულად წაკითხვა',
        'home.media.modal.takeaways': 'მთავარი აქცენტები',
        'home.media.modal.viewSource': 'წყაროზე გადასვლა',
        'home.media.modal.linkPending': 'წყარო დროებით მიუწვდომელია',
        'home.media.modal.allMedia': 'მედია არქივი',
        'home.media.modal.close': 'დახურვა',
        'home.hero.sponsorBadge': 'პარტნიორთა შერჩევა აქტიურია',
        'home.career.title': 'პროფესიული კარიერა',
        'home.career.viewFull': 'სრული კარიერული გზა',
        'home.highlights.viewGallery': 'სრული არქივი',
        'home.partners.title': 'პარტნიორები',
        'home.partners.collaborations': 'კომერციული პარტნიორები',
        'home.partners.sponsorship': 'სტრატეგიული თანამშრომლობა',
        'home.partners.primaryAvailable': 'მთავარი ციფრული პარტნიორი — ხელმისაწვდომია',
        'home.partners.officialAvailable': 'ოფიციალური პარტნიორები — შერჩევა აქტიურია',
        'home.forBrands.cta': 'პარტნიორობა ნინიაშვილთან',
        'page.contact.subtitle': 'მოთხოვნები და პროფესიული წარმომადგენლობა.',
        'home.authority.slogan': 'რასაც აკეთებ — გიყვარდეს მთელი გულით!',
        'home.authority.author': 'დავით ნინიაშვილი',
        'home.authority.positioning': 'გლობალური თამაში. ელიტარული ავტორიტეტი.',
        'home.authority.status': 'მიმდინარე პერიოდში — Top14: Stade Rochelais | საქართველოს ეროვნული ნაკრები',
        'home.authority.cta.career': 'პროფესიული კარიერა',
        'home.authority.cta.highlights': 'გამორჩეული მომენტები',
        'home.authority.kpis': [
            '4-გზის ევროპის ჩემპიონატის გამარჯვებული (2021–2024)',
            'EPCR Challenge Cup-ის გამარჯვებული — Lyon (2021–22)',
            '46 კეპი — საქართველო (დებიუტი 2020)',
            'Oscars du Midi Olympique-ის გამარჯვებული (2023)',
            'RugbyPass Top 100 მოთამაშე — #83 (2025)',
            'Barbarian F.C.-ის შემადგენლობაში თამაში — 80 წუთი (2022)',
        ],
        'home.authority.svg1.title': 'ევროპის ჩემპიონი',
        'home.authority.svg1.subline': '2021\u20132024',
        'home.authority.svg2.title': 'ჩელენჯ ქაფი',
        'home.authority.svg2.subline': 'გამარჯვებული — ლიონი',
        'home.authority.svg3.title': 'Top 100 მოთამაშე',
        'home.authority.svg3.subline': 'RugbyPass 2025',
        'page.bio.position': 'პოზიცია',
        'page.bio.currentTeam': 'მიმდინარე გუნდი',
        'page.bio.previousTeam': 'წინა გუნდი',
        'page.bio.nationality': 'მოქალაქეობა',
        'page.bio.birthDate': 'დაბადების თარიღი',
        'page.bio.about': 'ბიოგრაფია',
        'page.bio.loading': 'პროფილი ახლდება...',
        'page.bio.errorTitle': 'ინფორმაცია მიუწვდომელია',
        'page.bio.errorSub': 'გთხოვთ სცადოთ მოგვიანებით.',
        'page.bio.pending': 'ბიოგრაფია მზადდება.',
        'page.career.loading': 'მონაცემები იტვირთება...',
        'page.career.errorTitle': 'მონაცემები მიუწვდომელია',
        'page.career.errorSub': 'გთხოვთ სცადოთ მოგვიანებით.',
        'page.career.noStats': 'სტატისტიკა ჯერჯერობით არ ხელმისაწვდომია.',
        'page.career.awardsTitle': 'ჯილდოები და მიღწევები',
        'page.career.untitledAward': 'ჯილდო',
        'page.career.table.season': 'სეზონი',
        'page.career.table.team': 'გუნდი',
        'page.career.table.competition': 'ტურნირი',
        'page.career.table.matches': 'მატჩი',
        'page.career.table.tries': 'ლელო',
        'page.career.table.meters': 'მეტრი',
        'page.career.table.defendersBeaten': 'მოტყუებული მეტოქე',
        'page.career.table.lineBreaks': 'ხაზის გაჭრა',
        'page.career.table.offloads': 'ოფლოუდი',
        'page.career.table.wdl': 'მ-გ-წ',
        'page.career.table.starts': 'სტარტი',
        'page.career.table.points': 'ქულა',
        'page.career.table.cards': 'ბარათი',
        'page.career.table.minutes': 'წუთი',
        'page.career.section.overview': 'კარიერის მიმოხილვა',
        'page.career.section.seasons': 'სეზონების სტატისტიკა',
        'page.career.section.breakdown': 'ტურნირების ჭრილი',
        'page.career.meta.source': 'წყარო',
        'page.career.meta.lastUpdated': 'განახლდა',
        // NEW FOR BRANDS KEYS
        'page.forBrands.s1.eyebrow': 'ბიზნეს შესაძლებლობები',
        'page.forBrands.s1.title': 'ბრენდული პარტნიორობა და ციფრული კოლაბორაციის შესაძლებლობები',
        'page.forBrands.s1.sub': 'ოფიციალური პლატფორმა ბრენდების, სააგენტოებისა და კომერციული წარმომადგენლებისთვის.',
        'page.forBrands.s1.body': 'დავით ნინიაშვილის ოფიციალური ციფრული გარემო სთავაზობს პარტნიორებს თანამშრომლობის სტრუქტურირებულ მოდელებსა და ინტეგრაციის ფორმატებს.',
        'page.forBrands.s1.cta1': 'პარტნიორობის მოთხოვნა',
        'page.forBrands.s1.cta2': 'მედია-კიტის მიღება',
        'page.forBrands.s2.eyebrow': 'ღირებულება',
        'page.forBrands.s2.title': 'რატომ თანამშრომლობენ ბრენდები დავით ნინიაშვილთან',
        'page.forBrands.s2.sub': 'ათლეტის ავტორიტეტი და პერსონალური ბრენდის რეპუტაცია ქმნის პრემიუმ კომერციულ გარემოს.',
        'page.forBrands.s2.body': 'თანამშრომლობა ეფუძნება ათლეტის სპორტულ ავტორიტეტს და პერსონალური ბრენდის სტაბილურ ღირებულებას. მაღალი ხარისხის ბრენდული შესაბამისობა და ციფრული განვითარების პოტენციალი უზრუნველყოფს პარტნიორი ბრენდების ეფექტურ და სტრუქტურირებულ ინტეგრაციას თანამედროვე ციფრულ ეკოსისტემაში.',
        'page.forBrands.s3.eyebrow': 'ტაქსონომია',
        'page.forBrands.s3.title': 'პარტნიორობის მოდელების მიმოხილვა',
        'page.forBrands.s3.sub': 'კომერციული ურთიერთობების კლასიფიკაცია და სტრუქტურა.',
        'page.forBrands.s3.body': 'სისტემა გამოყოფს ბრენდულ კოლაბორაციას (Brand Partner) და ციფრული პლატფორმის პარტნიორობის დონეებს. ეს დაყოფა საშუალებას იძლევა მკაფიოდ განისაზღვროს თანამშრომლობის ფორმატი, მასშტაბი და ბრენდის წარმოდგენის არხები.',
        'page.forBrands.s4.eyebrow': 'კომერციული შეთავაზება',
        'page.forBrands.s4.title': 'ციფრული პარტნიორობის შესაძლებლობები',
        'page.forBrands.s4.sub': 'ბრენდული ინტეგრაციის ფორმატები ოფიციალურ პლატფორმაზე.',
        'page.forBrands.s4.body': 'წინამდებარე ბლოკი წარმოადგენს ციფრული პარტნიორობის მთავარ კომერციულ შეთავაზებას. Main Digital Partner სტატუსიდან დაწყებული, ვებსაიტის მხარდამჭერობამდე, თითოეული კატეგორია განსაზღვრავს ბრენდის ხილვადობის არეალსა და ინტეგრაციის ინსტრუმენტებს პლატფორმაზე.',
        'page.forBrands.s4.cta': 'პირობების განხილვა',
        'page.forBrands.s5.eyebrow': 'განმარტება',
        'page.forBrands.s5.title': 'განსხვავება ბრენდულ კოლაბორაციასა და ციფრულ პარტნიორობას შორის',
        'page.forBrands.s5.sub': 'კომერციული წარმომადგენლობისა და პლატფორმაზე ინტეგრაციის გამიჯვნა.',
        'page.forBrands.s5.body': 'ბრენდული კოლაბორაცია ფოკუსირებულია ათლეტის ფართო კომერციულ წარმომადგენლობაზე, ხოლო ციფრული პარტნიორობა გულისხმობს კონკრეტულად ამ პლატფორმის ციფრულ ეკოსისტემაში ინტეგრირებას.',
        'page.forBrands.s6.eyebrow': 'პლატფორმის როლი',
        'page.forBrands.s6.title': 'რატომ არის მნიშვნელოვანი ოფიციალური პლატფორმა',
        'page.forBrands.s6.sub': 'ოფიციალური ციფრული ყოფნა და სტრუქტურირებული ინტეგრაცია.',
        'page.forBrands.s6.body': 'პლატფორმა უზრუნველყოფს ბრენდების ორგანიზებულ წარმოდგენას ერთიან ციფრულ სივრცეში. ეს არის ზრდაზე ორიენტირებული გარემო, სადაც ბრენდის ინტეგრაცია ხდება მართვადი და სტრატეგიულად დაგეგმილი პროცესებით.',
        'page.forBrands.s7.eyebrow': 'რეპუტაცია',
        'page.forBrands.s7.title': 'შერჩეული ბრენდ-კოლაბორაციები',
        'page.forBrands.s7.sub': 'თანამშრომლობისა და პროფესიული ასოციაციების ისტორია.',
        'page.forBrands.s7.body': 'ეს სექცია წარმოადგენს ბრენდებთან მუშაობის გამოცდილებას და ემსახურება მხოლოდ რეპუტაციულ ასოციაციას. მოცემული ლოგოების არსებობა არ მიუთითებს Main Digital Partner, Digital Partner ან Website Supporter სტატუსზე.',
        'page.forBrands.s8.eyebrow': 'სანდოობა',
        'page.forBrands.s8.title': 'პროფესიული სტატუსი',
        'page.forBrands.s8.sub': 'ოფიციალური პლატფორმა და პარტნიორობის მზადყოფნა.',
        'page.forBrands.s8.body': 'დავით ნინიაშვილის ოფიციალური პლატფორმა წარმოადგენს ათლეტის მთავარ ციფრულ არხს, რომელიც ასახავს მის აქტიურ სპორტულ კარიერას და თანამშრომლობის გამოცდილებას. პლატფორმა სრულად არის მომზადებული სტრუქტურირებული კომერციული პარტნიორობისთვის.',
        'page.forBrands.s8.p1': 'Stade Rochelais — ელიტარული Top 14 და ჩემპიონთა თასი',
        'page.forBrands.s8.p2': 'საქართველოს ეროვნული ნაკრები — საერთაშორისო ასპარეზი',
        'page.forBrands.s8.p3': 'ოფიციალური ციფრული პლატფორმა დაფუძნებულია',
        'page.forBrands.s8.p4': 'სტრუქტურირებული კომერციული ეკოსისტემა და მედია-კიტი მზადაა',
        'page.forBrands.s9.eyebrow': 'კონვერტაცია',
        'page.forBrands.s9.title': 'მოთხოვნა პარტნიორობაზე',
        'page.forBrands.s9.sub': 'მოითხოვეთ მედია-კიტი ან გამოგვიგზავნეთ პარტნიორობის შემოთავაზება.',
        'page.forBrands.s9.body': 'ჩვენ განვიხილავთ ყველა პროფესიულ მოთხოვნას. ფორმის შევსებით თქვენ შეგიძლიათ მიიღოთ დეტალური მედია-კიტი ან დასვათ კითხვა პარტნიორობის კონკრეტულ კატეგორიებზე. პირდაპირი კავშირისთვის გამოიყენეთ ქვემოთ მითითებული საკონტაქტო ფორმატი.',
        'page.forBrands.s9.cta1': 'მოთხოვნის გაგზავნა',
        'page.forBrands.s9.cta2': 'მედია-კიტის მიღება',
        'page.forBrands.s10.title': 'დაიწყეთ კომერციული თანამშრომლობა',
        'page.forBrands.s10.sub': 'მიიღეთ დეტალური ინფორმაცია პარტნიორობის შესაძლებლობების შესახებ.',
        'page.forBrands.s10.cta1': 'ფორმის შევსება',
        'page.forBrands.s10.cta2': 'კონტაქტი',
        'page.forBrands.form.company': 'კომპანიის დასახელება',
        'page.forBrands.form.name': 'საკონტაქტო პირი',
        'page.forBrands.form.position': 'პოზიცია',
        'page.forBrands.form.email': 'ელ-ფოსტა',
        'page.forBrands.form.interest': 'პარტნიორობის ინტერესი',
        'page.forBrands.form.category': 'საინტერესო კატეგორია',
        'page.forBrands.form.message': 'შეტყობინება',
        'page.forBrands.form.submit': 'მოთხოვნის გაგზავნა',
        'page.forBrands.form.success': 'ლოკალური ვალიდაცია წარმატებულია.',
        'page.forBrands.cat.brand': 'Brand Partner',
        'page.forBrands.cat.brand.desc': 'ფართო კომერციული თანამშრომლობა და ბრენდული კოლაბორაცია.',
        'page.forBrands.cat.mainDigital': 'Main Digital Partner',
        'page.forBrands.cat.mainDigital.desc': 'პლატფორმის წამყვანი ციფრული პარტნიორი.',
        'page.forBrands.cat.digital': 'Digital Partner',
        'page.forBrands.cat.digital.desc': 'ციფრული ეკოსისტემის სტრატეგიული პარტნიორი.',
        'page.forBrands.cat.supporter': 'Website Supporter',
        'page.forBrands.cat.supporter.desc': 'პლატფორმის ციფრული მხარდამჭერი.',
        'page.forBrands.form.interest.inquiry': 'პარტნიორობის მოთხოვნა',
        'page.forBrands.form.interest.mediakit': 'მედია-კიტის მოთხოვნა',
        'page.forBrands.form.fallback': 'პირდაპირი კავშირისთვის:'
    },
    fr: {
        'nav.home': 'ACCUEIL',
        'nav.bio': 'BIO',
        'nav.career': 'CARRI\u00c8RE',
        'nav.gallery': 'GALERIE',
        'nav.highlights': 'TEMPS FORTS',
        'nav.contact': 'CONTACT',
        'nav.media': 'M\u00c9DIAS',
        'nav.partners': 'PARTENAIRES',
        'nav.forBrands': 'POUR LES MARQUES',
        'page.media.title': 'Médias',
        'page.media.subtitle': 'Archive des couvertures internationales et chronologie des sources d’autorité autour de Davit Niniashvili',
        'page.media.stats.records': 'Documents',
        'page.media.stats.tierA': 'Sources Catégorie A',
        'page.media.stats.languages': 'Langues',
        'page.media.filters.all': 'Tout',
        'page.media.filters.source': 'Source',
        'page.media.filters.year': 'Année',
        'page.media.filters.language': 'Langue',
        'page.media.filters.type': 'Format',
        'page.media.filters.tier': 'Catégorie',
        'page.media.filters.featuredOnly': 'À la Une',
        'page.media.filters.reset': 'Réinitialiser',
        'page.media.archive.title': 'Archives Médias',
        'page.media.pending.title': 'En Attente de Vérification',
        'page.media.pending.subtitle': 'Documents provisoires en attente de métadonnées',
        'page.media.viewSource': 'Voir la Source',
        'page.media.linkPending': 'Lien en Attente',
        'page.media.backHome': 'Retour à l\'Accueil',
        'page.partners.title': 'Partenaires',
        'page.partners.subtitle': 'Un \u00e9cosyst\u00e8me strat\u00e9gique de collaborations mondiales.',
        'home.media.title': 'Médias Internationaux',
        'home.media.subtitle': 'Couvertures médiatiques internationales récentes autour de Davit Niniashvili',
        'home.media.viewAll': 'Tout l\'espace média',
        'home.media.open': 'Lire l\'Article Complet',
        'home.media.modal.takeaways': 'Points Clés',
        'home.media.modal.viewSource': 'Voir la Source Originale',
        'home.media.modal.linkPending': 'Source Actuellement Hors Ligne',
        'home.media.modal.allMedia': 'Voir les Archives',
        'home.media.modal.close': 'Fermer',
        'home.hero.sponsorBadge': 'Sélection de partenaires active',
        'home.career.title': 'Carri\u00e8re Professionnelle',
        'home.career.viewFull': 'Explorer la carri\u00e8re compl\u00e8te',
        'home.highlights.viewGallery': 'Explorer l\'archive compl\u00e8te',
        'home.partners.title': 'Partenaires',
        'home.partners.collaborations': 'Partenaires Commerciaux',
        'home.partners.sponsorship': 'Partenariats Strat\u00e9giques',
        'home.partners.primaryAvailable': 'Partenaire digital principal \u2014 Disponible',
        'home.partners.officialAvailable': 'Partenaires officiels \u2014 S\u00e9lection active',
        'home.forBrands.cta': 'Collaborer avec Niniashvili',
        'page.contact.subtitle': 'Inqu\u00eates et repr\u00e9sentation professionnelle.',
        'home.authority.slogan': 'Aime ce que tu fais \u2014 de tout c\u0153ur!',
        'home.authority.author': 'Davit Niniashvili',
        'home.authority.positioning': 'Performance Mondiale. Autorit\u00e9 d\'\u00c9lite.',
        'home.authority.status': 'Actuellement \u2014 Top14: Stade Rochelais | \u00c9quipe nationale de G\u00e9orgie',
        'home.authority.cta.career': 'Carri\u00e8re Professionnelle',
        'home.authority.cta.highlights': 'Moments Forts',
        'home.authority.kpis': [
            '4\u00d7 Vainqueur du Championnat d\u2019Europe de Rugby (2021\u20132024)',
            'Vainqueur EPCR Challenge Cup \u2014 Lyon (2021\u201322)',
            '46 s\u00e9lections internationales \u2014 G\u00e9orgie (d\u00e9but 2020)',
            'Laur\u00e9at Oscars du Midi Olympique (2023)',
            'Joueur RugbyPass Top 100 \u2014 #83 (2025)',
            'Barbarian F.C. \u2014 80 minutes (2022)',
        ],
        'home.authority.svg1.title': 'Champion d\'Europe',
        'home.authority.svg1.subline': '2021\u20132024',
        'home.authority.svg2.title': 'Challenge Cup',
        'home.authority.svg2.subline': 'Vainqueur \u2014 Lyon',
        'home.authority.svg3.title': 'Top 100 Joueur',
        'home.authority.svg3.subline': 'RugbyPass 2025',
        'page.bio.position': 'Poste',
        'page.bio.currentTeam': '\u00c9quipe Actuelle',
        'page.bio.previousTeam': '\u00c9quipe Pr\u00e9c\u00e9dente',
        'page.bio.nationality': 'Nationalit\u00e9',
        'page.bio.birthDate': 'Date de Naissance',
        'page.bio.about': '\u00c0 Propos',
        'page.bio.loading': 'Mise \u00e0 jour du profil...',
        'page.bio.errorTitle': 'Information non disponible',
        'page.bio.errorSub': 'Veuillez r\u00e9essayer plus tard.',
        'page.bio.pending': 'Description du profil en cours.',
        'page.career.loading': 'Chargement des donn\u00e9es de carri\u00e8re...',
        'page.career.errorTitle': 'Donn\u00e9es non disponibles',
        'page.career.errorSub': 'Veuillez r\u00e9essayer plus tard.',
        'page.career.noStats': 'Aucune statistique enregistr\u00e9e pour le moment.',
        'page.career.awardsTitle': 'Prix et Distinctions',
        'page.career.untitledAward': 'Prix',
        'page.career.table.season': 'Saison',
        'page.career.table.team': '\u00c9quipe',
        'page.career.table.competition': 'Comp\u00e9tition',
        'page.career.table.matches': 'Matchs',
        'page.career.table.tries': 'Essais',
        'page.career.table.meters': 'M\u00e8tres',
        'page.career.table.defendersBeaten': 'D\u00e9fenseurs battus',
        'page.career.table.lineBreaks': 'Franchissements',
        'page.career.table.offloads': 'Offloads',
        'page.career.table.wdl': 'V-N-D',
        'page.career.table.starts': 'Titulaire',
        'page.career.table.points': 'Points',
        'page.career.table.cards': 'Cartons',
        'page.career.table.minutes': 'Minutes',
        'page.career.section.overview': 'Vue d\'ensemble',
        'page.career.section.seasons': 'Statistiques par saison',
        'page.career.section.breakdown': 'R\u00e9partition par comp\u00e9tition',
        'page.career.meta.source': 'Source',
        'page.career.meta.lastUpdated': 'Mise à jour',
        // NEW FOR BRANDS KEYS
        'page.forBrands.s1.eyebrow': 'Opportunités Commerciales',
        'page.forBrands.s1.title': 'Partenariat de Marque & Opportunités Numériques',
        'page.forBrands.s1.sub': 'La plateforme officielle pour les marques, agences et représentants commerciaux.',
        'page.forBrands.s1.body': 'L\'environnement numérique officiel de Davit Niniashvili offre aux partenaires des modèles de collaboration et des formats d\'intégration structurés.',
        'page.forBrands.s1.cta1': 'Demande de Partenariat',
        'page.forBrands.s1.cta2': 'Demander le Kit Média',
        'page.forBrands.s2.eyebrow': 'Valeur',
        'page.forBrands.s2.title': 'Pourquoi les marques s\'associent-elles à Davit Niniashvili',
        'page.forBrands.s2.sub': 'L\'autorité sportive et la réputation de la marque personnelle créent un environnement commercial premium.',
        'page.forBrands.s2.body': 'La collaboration repose sur l\'autorité sportive de l\'athlète et la valeur stable de sa marque personnelle. Un alignement de qualité et un potentiel de croissance assurent une intégration structurée.',
        'page.forBrands.s3.eyebrow': 'Taxonomie',
        'page.forBrands.s3.title': 'Aperçu des Modèles de Partenariat',
        'page.forBrands.s3.sub': 'Classification et structure des relations commerciales.',
        'page.forBrands.s3.body': 'Le système sépare les collaborations Brand Partner des niveaux Digital Partner. Cela permet de définir clairement les formats de collaboration.',
        'page.forBrands.s4.eyebrow': 'Offre Commerciale',
        'page.forBrands.s4.title': 'Opportunités de Partenariat Numérique',
        'page.forBrands.s4.sub': 'Formats pour l\'intégration de marque sur la plateforme officielle.',
        'page.forBrands.s4.body': 'Cette section présente l\'offre commerciale principale pour les partenariats numériques. De Main Digital Partner à Website Supporter, chaque catégorie définit l\'étendue de la visibilité sur la plateforme.',
        'page.forBrands.s4.cta': 'Voir les Conditions',
        'page.forBrands.s5.eyebrow': 'Clarification',
        'page.forBrands.s5.title': 'Partenariat de Marque vs Partenariat Numérique',
        'page.forBrands.s5.sub': 'Séparation de la représentation commerciale et de l\'intégration plateforme.',
        'page.forBrands.s5.body': 'Brand Partnership se concentre sur la représentation commerciale large, tandis que Digital Partnership concerne spécifiquement l\'intégration dans l\'écosystème numérique de cette plateforme.',
        'page.forBrands.s6.eyebrow': 'Rôle de la Plateforme',
        'page.forBrands.s6.title': 'Pourquoi la plateforme officielle est importante',
        'page.forBrands.s6.sub': 'Présence numérique officielle et intégration structurée.',
        'page.forBrands.s6.body': 'La plateforme assure un affichage organisé des marques dans un espace numérique unifié, géré via une planification stratégique orientée croissance.',
        'page.forBrands.s7.eyebrow': 'Réputation',
        'page.forBrands.s7.title': 'Collaborations de Marques Sélectionnées',
        'page.forBrands.s7.sub': 'Historique des collaborations et associations professionnelles.',
        'page.forBrands.s7.body': 'Cette section montre les collaborations de marque préalables ou existantes (association strictement réputationnelle). Ces logos ne signifient pas un statut Main Digital Partner, Digital Partner ou Website Supporter.',
        'page.forBrands.s8.eyebrow': 'Crédibilité',
        'page.forBrands.s8.title': 'Statut Professionnel',
        'page.forBrands.s8.sub': 'Plateforme officielle et préparation au partenariat.',
        'page.forBrands.s8.body': 'La plateforme officielle est le canal numérique principal de l\'athlète, reflétant une carrière sportive active et une expérience de collaboration. Elle est prête pour des partenariats commerciaux structurés.',
        'page.forBrands.s8.p1': 'Stade Rochelais — Élite Top 14 et Champions Cup',
        'page.forBrands.s8.p2': 'Équipe Nationale de Géorgie — Performance Internationale',
        'page.forBrands.s8.p3': 'Plateforme Numérique Officielle Établie',
        'page.forBrands.s8.p4': 'Écosystème Commercial Structuré et Kit Média Prêts',
        'page.forBrands.s9.eyebrow': 'Conversion',
        'page.forBrands.s9.title': 'Demande de Partenariat',
        'page.forBrands.s9.sub': 'Demandez un kit média ou soumettez une proposition de partenariat.',
        'page.forBrands.s9.body': 'Nous examinons toutes les demandes professionnelles. En remplissant ce formulaire, vous pouvez recevoir un kit média détaillé ou poser des questions sur des catégories spécifiques.',
        'page.forBrands.s9.cta1': 'Soumettre la Demande',
        'page.forBrands.s9.cta2': 'Obtenir le Kit Média',
        'page.forBrands.s10.title': 'Démarrer une Collaboration Commerciale',
        'page.forBrands.s10.sub': 'Obtenez des informations détaillées sur les opportunités.',
        'page.forBrands.s10.cta1': 'Remplir le Formulaire',
        'page.forBrands.s10.cta2': 'Contact',
        'page.forBrands.form.company': 'Nom de l\'entreprise',
        'page.forBrands.form.name': 'Personne de Contact',
        'page.forBrands.form.position': 'Fonction',
        'page.forBrands.form.email': 'Email',
        'page.forBrands.form.interest': 'Intérêt de Partenariat',
        'page.forBrands.form.category': 'Catégorie d\'intérêt',
        'page.forBrands.form.message': 'Message',
        'page.forBrands.form.submit': 'Soumettre la Demande',
        'page.forBrands.form.success': 'Validation du formulaire locale réussie.',
        'page.forBrands.cat.brand': 'Brand Partner',
        'page.forBrands.cat.brand.desc': 'Collaboration commerciale plus large et intégration de la marque.',
        'page.forBrands.cat.mainDigital': 'Main Digital Partner',
        'page.forBrands.cat.mainDigital.desc': 'Le principal partenaire numérique de la plateforme.',
        'page.forBrands.cat.digital': 'Digital Partner',
        'page.forBrands.cat.digital.desc': 'Un partenaire stratégique de l\'écosystème numérique.',
        'page.forBrands.cat.supporter': 'Website Supporter',
        'page.forBrands.cat.supporter.desc': 'Soutien numérique de la plateforme.',
        'page.forBrands.form.interest.inquiry': 'Demande de Partenariat',
        'page.forBrands.form.interest.mediakit': 'Demande de Kit Média',
        'page.forBrands.form.fallback': 'Pour un contact direct:'
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem('site_lang');
        if (saved && ['ka', 'fr', 'en'].includes(saved)) {
            return saved;
        }
        const browserLang = navigator.language || navigator.languages?.[0];
        if (browserLang) {
            if (browserLang.toLowerCase().startsWith('ka')) return 'ka';
            if (browserLang.toLowerCase().startsWith('fr')) return 'fr';
        }
        return 'en';
    });

    useEffect(() => {
        localStorage.setItem('site_lang', language);
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
